### ISSUE TITLE
completion_date not set for F2F

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tcs-loader#120]
It seems that the completion_date column in the cost_transaction table is not getting set for F2F challenges.  I see it getting set on other challenge types. 

Please update the loader to load completion_date for F2F challenges.  I believe we can just use the same logic that other challenge types are using.  The completion_date is set in the project_info table where project_info_type_id = 21.

Thanks

**Comment by ajefts** [comment]
fyi @ajaysaini9782 @RiteshTC

**Comment by ajaysaini9782** [comment]
@ajefts 
Loader script has been updated.
First2finish challenge completion date will update in next load.

**Comment by ajaysaini9782** [comment]
Now completion date is getting set for First2Finish challenges as well.
