### ISSUE TITLE
Feature: Cron Job to Delete Admin Payments

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/tcs-loader#145]
Auto set the status of Admin Payments.
Sometimes, when TC Admins close out a payment task the system generates payments in PACTS and Online Review.

The Cron Job will monitor such payments and set the status to Deleted, and set the paid amount to zero in Online Review.

The Job should support 2 features
1) BA -  If a BA is provided, all payments in the BA should be marked as Deleted. (irrespective of the user used to generate payment)
2) UserId  - If a UserID is provided, all payments generated for a UserId should be marked as Deleted. (Irrespective of BA used)

**Comment by RiteshTC** [comment]
For first prize, please delete both instalments of payment.

**Comment by ajaysaini9782** [comment]
Loader has been done and deployed.
