### ISSUE TITLE
Connect Form Intake Parser cannot handle Multiple Brackets in key Name

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/tcs-loader#158]
If the key name has multiple brackets eg
taasDefinition.specialists[0].skills[1].name
the output name only removes the first bracket

**Comment by RiteshTC** [comment]
@ajaysaini9782 
Please validate the fix and incorporate in dev branch
https://github.com/topcoder-platform/tcs-loader/pull/157

**Comment by ajaysaini9782** [comment]
Changes have been validated and deployed to prod.
