### ISSUE TITLE
Store Deleted Payment Ids in a table in Looker

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/tcs-loader#166]
Store the Deleted Payment Ids in a table in Looker.
Create a new schema Adhoc in Redshift.
Create a new table to store Deleted payment Ids.

~~Store the payment ID record and current timestamp in the new table.~~
EDIT: Load all deleted payments as a new loader. Use the same logic as in Current TC_Payments Loader. 
i.e. the new loader will load deleted payments in Redshift

**Comment by ajaysaini9782** [comment]
Loader has been completed and deployed.
