### ISSUE TITLE
Feature: Jive Delete Query on Topgear Challenges

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/tcs-loader#199]
Run the Jive Delete Query on F2F challenges related with Topgear.
i.e. in addition to tasks, F2F challenge category, with zero messages should be included in deletion criteria.

Run the job every 6 hours, instead of once a day as now. i.e the job should run 4 times a day with a batch size of 75.

Make the previous days configurable via env variable with default days being 30

**Comment by ajaysaini9782** [comment]
Code has been updated and deployed.
