### ISSUE TITLE
Need more fields in ProjectStream data in looker

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tcs-loader#85]
Total_Actual_Challenge_Fee__c
Total_Actual_Member_Payment__c
Total_Invoiced_Amount__c

We need to rename field corresponding to Salesforce field `Remaining_Billed_Amount__c` to `Remaining Invoiced Budget` instead of current `Remaining Billed Amount`

**Comment by ajaysaini9782** [comment]
Above fields have been added in project stream loader.
